server:
  port: 8851 # 端口

spring:
  application:
    name: nacos-test

  datasource:
    url: jdbc:mysql://192.168.176.128:3306/seata_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123

  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        server-addr: 192.168.176.128:8848

# Seata 配置项，对应 SeataProperties 类
seata:
  enabled: true #开启seata支持
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  enable-auto-data-source-proxy: true
  tx-service-group: my_test_tx_group # Seata 事务组编号，用于 TC 集群名
  #seata整合nacos配置中心
  config:
    type: nacos
    nacos:
      group: default #seata服务注册到nacos的组名SEATA_GROUP
      server-addr: 192.168.176.128:8848
  # Seata 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroupMapping:
      my_test_tx_group: default
  # Seata 注册中心配置项，对应 RegistryProperties 类
  registry:
    type: nacos # 注册中心类型，默认为 file
    nacos:
      group: default # 使用的 Seata 分组
      namespace: # Nacos 命名空间
      serverAddr: 192.168.176.128:8848 # Nacos 服务地址