server:
  port: 8852

spring:
  application:
    name: nacos-provider

  datasource:
    url: jdbc:mysql://192.168.176.128:3306/seata_storage?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123

  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        server-addr: 192.168.176.128:8848
    sentinel:
      eager: true # 是否饥饿加载。默认为 false 关闭
      transport:
        dashboard: 127.0.0.1:7070 # Sentinel 控制台地址

management:
  endpoints:
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
  endpoint:
    # Health 端点配置项，对应 HealthProperties 配置类
    health:
      enabled: true # 是否开启。默认为 true 开启。
      show-details: ALWAYS # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。

# Seata 配置项，对应 SeataProperties 类
seata:
  enabled: true #开启seata支持
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  enable-auto-data-source-proxy: true
  tx-service-group: system-server-group # Seata 事务组编号，用于 TC 集群名
  #seata整合nacos配置中心
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP #seata服务注册到nacos的组名SEATA_GROUP
      server-addr: 192.168.176.128:8848
  # Seata 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroupMapping:
      system-server-group: SEATA_GROUP
  # Seata 注册中心配置项，对应 RegistryProperties 类
  registry:
    type: nacos # 注册中心类型，默认为 file
    nacos:
      group: SEATA_GROUP # 使用的 Seata 分组
      serverAddr: 192.168.176.128:8848 # Nacos 服务地址