server:
  port: 8181
spring:
  application:
    name: gateway
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        # 路由的编号
        - id: first-one
          # 路由到的目标地址
          uri: https://www.baidu.com/
          # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
          predicates:
            - Path=/first
          filters:
            - StripPrefix=1
            # 路由的编号
        - id: second-one
            # 路由到的目标地址
          uri: https://www.qq.com/
          # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
          predicates:
            - Path=/second
          filters:
            - StripPrefix=1
        - id: thrid-one
          # 路由到的目标地址
          uri: lb://nacos-sentinel
          # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
          predicates:
            - Path=/sentinel/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        # Nacos 服务器地址
        server-addr: 10.130.250.136:80
        namespace: 5bae13dc-4258-4249-a18a-a33da545cd53 #--dev
management:
  endpoints:
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。