server:
  port: 8150
spring:
  application:
    name: nacos-consumer
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 10.130.250.136:80
        # Nacos 服务器地址
        #service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
        #namespace: 4a95fbe6-b308-4da0-a42d-e3038c6d5350 # Nacos 命名空间 dev 的编号
management:
  endpoints:
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
  endpoint:
    # Health 端点配置项，对应 HealthProperties 配置类
    health:
      enabled: true # 是否开启。默认为 true 开启。
      show-details: ALWAYS # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。
seata:
  registry:
    type: nacos # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    nacos:
      server-addr: 10.130.250.136:80
      namespace: "" # namespace，默认为空
      group: DEFAULT_GROUP # 分组，默认是DEFAULT_GROUP
      application: seata-server # seata服务名称
      username: nacos
      password: nacos
  tx-service-group: seata-demo # 事务组名称
  service:
    vgroup-mapping: # 事务组与cluster的映射关系
      seata-demo: SSS
  config:
    type: nacos
    nacos:
      server-addr: 10.130.250.136:80
      username: nacos
      password: nacos
      group: DEFAULT_GROUP
      data-id: client.properties
