spring:
   cloud:
      nacos:
        # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
        discovery:
           server-addr: 127.0.0.1:8848
           # Nacos 服务器地址
           #service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
           namespace: 4a95fbe6-b308-4da0-a42d-e3038c6d5350 # Nacos 命名空间 dev 的编号
   # Sentinel 配置项
      sentinel:
        eager: true # 是否饥饿加载。默认为 false 关闭
        transport:
          dashboard: 127.0.0.1:7070 # Sentinel 控制台地址